<?php

namespace Tests;

use App\Enums\Area;
use App\Enums\Role;
use App\Models\Company;
use App\Models\User;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use Modules\Grantify\Facades\Grantify;
use Modules\Otpify\Facades\Otpify;
use Modules\Otpify\Models\OtpifyCode;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;

    public User $user;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        Artisan::call('module:seed');
        $this->user = User::factory()->create();
    }

    protected function login(string $role = Role::Admin, string $test = null): string
    {
        $email = 'a@a.aa';
        $passwordPlainText = '12345678';
        $passwordEncrypted = bcrypt('12345678');
        $source = 'admin';

        // create user
        $user = User::factory()->create([
            'email' => $email,
            'password' => $passwordEncrypted,
        ]);

        Grantify::assignRoleToModel($user, $role);

        if ($test == null) {
            $this->actingAs($user);
        }

        // login user
        $loginResponse = $this->postJson('api/v1/auth/login', [
            'email' => $email,
            'password' => $passwordPlainText,
            'source' => $source,
        ]);

        $loginResponse->assertStatus(200)->assertJsonStructure([
            'data' => ['token'],
        ]);

        return $loginResponse->getOriginalContent()['data']['token'];
    }

      protected function lenderLogin(string $role, string $test = null, ?Company $company)
      {
          $email = 'a@a.aa';
          $passwordPlainText = '12345678';
          $passwordEncrypted = bcrypt('12345678');
          $source = 'admin';

          $campany = $company ?? Company::factory()->create();

          // create user
          $user = User::factory()->create([
              'email' => $email,
              'password' => $passwordEncrypted,
              'company_id' => $campany->id,
          ]);

          Grantify::assignRoleToModel($user, $role);

          if ($test == null) {
              $this->actingAs($user);
          }

          // login user
          $loginResponse = $this->postJson('api/v1/auth/login', [
              'email' => $email,
              'password' => $passwordPlainText,
              'source' => $source,
              'unique_name' => $campany->unique_name,
          ]);

          $loginResponse->assertStatus(200)->assertJsonStructure([
              'data' => ['token'],
          ]);

          return $loginResponse->getOriginalContent()['data']['token'];
      }

    protected function createOtpifyCode(int $code, int $otpifiableId, array $data = []): Builder|Model
    {
        return OtpifyCode::query()->create([
            'id' => (string) Str::uuid(),
            'initiator_id' => auth()->user()->getAuthIdentifier(),
            'initiator_type' => (new User())->getMorphClass(),
            'otpifiable_id' => $otpifiableId,
            'otpifiable_type' => (new User())->getMorphClass(),
            'otp_code' => Hash::make($code),
            'expiration_date' => now()->addMinutes(config('otpify.code_expiration_time')),
            'data' => $data,
        ]);
    }

    protected function createUserAuthorizationToken(): string
    {
        return Otpify::generateAuthorizationToken([
            'user_id' => auth()->id(),
            'area' => Area::SuperAdmin,
        ]);
    }
}
