name: Deployment to Dev

on:
  #push:
  # branches:
  #  - dev

jobs:
  deploy_to_dev:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy code
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ vars.DEPLOY_HOST }} "cd /var/www/lynk-backend && sudo git pull && 
          sudo composer install --no-interaction --optimize-autoloader && 
          sudo php artisan migrate --no-interaction --force && 
          sudo supervisorctl restart all &&
          php artisan module:seed --class=GrantifyDatabaseSeeder Grantify &&
          php artisan optimize:clear  "
