<?php

namespace App\Support\DocumentEngine;

use App\Support\DocumentEngine\Generators\BursamBidCertificatePdf;
use App\Support\DocumentEngine\Generators\BursamOtcCertificatePdf;
use App\Support\DocumentEngine\Generators\BursamStbCertificatePdf;
use App\Support\DocumentEngine\Generators\ClientWakalaPdf;
use App\Support\DocumentEngine\Generators\SellConfirmationDocumentPdf;
use App\Support\DocumentEngine\Generators\SellingCommodityToCustomerPdf;
use App\Support\DocumentEngine\Generators\SellingPledgeCertificatePdf;
use App\Support\DocumentEngine\Generators\TransferOwnershipToLenderPdf;
use App\Support\DocumentEngine\Generators\VoucherReceiptPdf;
use App\Support\DocumentEngine\Generators\ZatcaInvoicePdf;
use InvalidArgumentException;

class PdfFactory
{
    protected static array $map = [
        'client_wakala' => ClientWakalaPdf::class,
        'transfer_ownership_to_lender' => TransferOwnershipToLenderPdf::class,
        'selling_commodity_to_customer' => SellingCommodityToCustomerPdf::class,
        'sell_confirmation_document' => SellConfirmationDocumentPdf::class,
        'bursam_bid_certificate' => BursamBidCertificatePdf::class,
        'bursam_stb_certificate' => BursamStbCertificatePdf::class,
        'bursam_otc_certificate' => BursamOtcCertificatePdf::class,
        'selling_pledge_certificate' => SellingPledgeCertificatePdf::class,

        // generated by actions to wallet topup and trader order
        'voucher_receipt' => VoucherReceiptPdf::class,
        'zatca_invoice' => ZatcaInvoicePdf::class,
    ];

    public static function make(string $type): BasePdfGenerator
    {
        if (! isset(self::$map[$type])) {
            throw new InvalidArgumentException("Unknown PDF type: $type");
        }

        return app(self::$map[$type]);
    }
}
