services:
  local-market-commodities-settlement-worker:
    image: app-php-fpm:latest
    working_dir: /var/www/html
    restart: unless-stopped
    env_file:
      - ../../.env
    command: php artisan queue:work redis --verbose --tries=50 --timeout=120 --queue=local_market_commodities_settlement
    depends_on:
      - app
    healthcheck:
      test: ["CMD", "php", "-r", "exit(0);"]
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 8
    networks:
      - laravel

  local-market-eligible-quantities-worker:
    image: app-php-fpm:latest
    working_dir: /var/www/html
    restart: unless-stopped
    env_file:
      - ../../.env
    command: php artisan queue:work redis --verbose --tries=5 --timeout=120 --queue=local_market_eligible_quantities
    depends_on:
      - app
    healthcheck:
      test: ["CMD", "php", "-r", "exit(0);"]
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 8
    networks:
      - laravel

  local-market-order-inventories-units-logging:
    image: app-php-fpm:latest
    working_dir: /var/www/html
    restart: unless-stopped
    env_file:
      - ../../.env
    command: php artisan queue:work redis --verbose --tries=5 --timeout=120 --queue=local_market_order_inventories_units_logging
    depends_on:
      - app
    healthcheck:
      test: ["CMD", "php", "-r", "exit(0);"]
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 5
    networks:
      - laravel

  local-market-order-initiation:
    image: app-php-fpm:latest
    working_dir: /var/www/html
    restart: unless-stopped
    env_file:
      - ../../.env
    command: php artisan queue:work redis --verbose --tries=5 --timeout=120 --queue=local_market_order_initiation
    depends_on:
      - app
    healthcheck:
      test: ["CMD", "php", "-r", "exit(0);"]
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 5
    networks:
      - laravel

  trader-order-initiation:
    image: app-php-fpm:latest
    working_dir: /var/www/html
    restart: unless-stopped
    env_file:
      - ../../.env
    command: php artisan queue:work redis --verbose --tries=5 --timeout=120 --queue=trader_order_initiation
    depends_on:
      - app
    healthcheck:
      test: ["CMD", "php", "-r", "exit(0);"]
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 5
    networks:
      - laravel

  complete-commodities-purchased-local-market-worker:
    image: app-php-fpm:latest
    working_dir: /var/www/html
    restart: unless-stopped
    env_file:
      - ../../.env
    command: php artisan queue:work redis --verbose --tries=5 --timeout=120 --queue=complete_commodities_purchased_local_market
    depends_on:
      - app
    healthcheck:
      test: ["CMD", "php", "-r", "exit(0);"]
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 5
    networks:
      - laravel

  buy-commodities-local-market-orders-worker:
    image: app-php-fpm:latest
    working_dir: /var/www/html
    restart: unless-stopped
    env_file:
      - ../../.env
    command: php artisan queue:work redis --verbose --tries=5 --timeout=120 --queue=buy_commodities_local_market_orders
    depends_on:
      - app
    healthcheck:
      test: ["CMD", "php", "-r", "exit(0);"]
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 5
    networks:
      - laravel

  apply-order-fees-worker:
    image: app-php-fpm:latest
    working_dir: /var/www/html
    restart: unless-stopped
    env_file:
      - ../../.env
    command: php artisan queue:work redis --verbose --tries=3 --timeout=120 --queue=apply_order_fees
    depends_on:
      - app
    healthcheck:
      test: ["CMD", "php", "-r", "exit(0);"]
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 1
    networks:
      - laravel

networks:
  laravel:
