services:
  local-market-states-worker:
    image: app-php-fpm:latest
    working_dir: /var/www/html
    restart: unless-stopped
    env_file:
      - ../../.env
    command: php artisan queue:work redis --verbose --tries=5 --timeout=120 --queue=local_market_states
    depends_on:
      - app
    healthcheck:
      test: ["CMD", "php", "-r", "exit(0);"]
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 8
    networks:
      - laravel

  local-market-process-worker:
    image: app-php-fpm:latest
    working_dir: /var/www/html
    restart: unless-stopped
    env_file:
      - ../../.env
    command: php artisan queue:work redis --verbose --tries=5 --timeout=120 --queue=local_market_process
    depends_on:
      - app
    healthcheck:
      test: ["CMD", "php", "-r", "exit(0);"]
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 8
    networks:
      - laravel

  local-market-eligible-quantities-worker:
    image: app-php-fpm:latest
    working_dir: /var/www/html
    restart: unless-stopped
    env_file:
      - ../../.env
    command: php artisan queue:work redis --verbose --tries=5 --timeout=120 --queue=local_market_eligible_quantities
    depends_on:
      - app
    healthcheck:
      test: ["CMD", "php", "-r", "exit(0);"]
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 8
    networks:
      - laravel

  hold-eligible-local-order-units-worker:
    image: app-php-fpm:latest
    working_dir: /var/www/html
    restart: unless-stopped
    env_file:
      - ../../.env
    command: php artisan queue:work redis --verbose --tries=3 --timeout=120 --queue=hold_eligible_units_local_market_orders
    depends_on:
      - app
    healthcheck:
      test: ["CMD", "php", "-r", "exit(0);"]
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 5
    networks:
      - laravel

  complete-commodities-purchased-local-market-worker:
    image: app-php-fpm:latest
    working_dir: /var/www/html
    restart: unless-stopped
    env_file:
      - ../../.env
    command: php artisan queue:work redis --verbose --tries=5 --timeout=120 --queue=complete_commodities_purchased_local_market
    depends_on:
      - app
    healthcheck:
      test: ["CMD", "php", "-r", "exit(0);"]
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 5
    networks:
      - laravel

  refresh-eligibilities-worker:
    image: app-php-fpm:latest
    working_dir: /var/www/html
    restart: unless-stopped
    env_file:
      - ../../.env
    command: php artisan queue:work redis --verbose --tries=3 --timeout=120 --queue=refresh_eligibilities
    depends_on:
      - app
    healthcheck:
      test: ["CMD", "php", "-r", "exit(0);"]
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 1
    networks:
      - laravel

  notifications-worker:
    image: app-php-fpm:latest
    working_dir: /var/www/html
    restart: unless-stopped
    env_file:
      - ../../.env
    command: php artisan queue:work redis --verbose --tries=3 --timeout=120 --queue=notifications
    depends_on:
      - app
    healthcheck:
      test: ["CMD", "php", "-r", "exit(0);"]
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 5
    networks:
      - laravel

  create-trader-orders-worker:
    image: app-php-fpm:latest
    working_dir: /var/www/html
    restart: unless-stopped
    env_file:
      - ../../.env
    command: php artisan queue:work redis --verbose --tries=5 --timeout=120 --queue=create_trader_orders
    depends_on:
      - app
    healthcheck:
      test: ["CMD", "php", "-r", "exit(0);"]
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 8
    networks:
      - laravel

  default-worker:
    image: app-php-fpm:latest
    working_dir: /var/www/html
    restart: unless-stopped
    env_file:
      - ../../.env
    command: php artisan queue:work redis --verbose --tries=5 --timeout=120 --queue=default
    depends_on:
      - app
    healthcheck:
      test: ["CMD", "php", "-r", "exit(0);"]
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 8
    networks:
      - laravel

  bursam-worker:
    image: app-php-fpm:latest
    working_dir: /var/www/html
    restart: unless-stopped
    env_file:
      - ../../.env
    command: php artisan queue:work redis --verbose --tries=3 --timeout=120 --queue=bursam
    depends_on:
      - app
    healthcheck:
      test: ["CMD", "php", "-r", "exit(0);"]
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 1
    networks:
      - laravel

  complete-purchasing-local-market-orders-worker:
    image: app-php-fpm:latest
    working_dir: /var/www/html
    restart: unless-stopped
    env_file:
      - ../../.env
    command: php artisan queue:work redis --verbose --tries=5 --timeout=120 --queue=complete_purchasing_local_market_orders
    depends_on:
      - app
    healthcheck:
      test: ["CMD", "php", "-r", "exit(0);"]
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 5
    networks:
      - laravel

  message-queue-worker:
    image: app-php-fpm:latest
    working_dir: /var/www/html
    restart: unless-stopped
    env_file:
      - ../../.env
    command: php artisan queue:work redis --verbose --tries=5 --timeout=120 --queue=mq
    depends_on:
      - app
    healthcheck:
      test: ["CMD", "php", "-r", "exit(0);"]
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 2
    networks:
      - laravel

networks:
  laravel:
