services:
  local-market-webhooks-worker:
    image: app-php-fpm:latest
    working_dir: /var/www/html
    restart: unless-stopped
    env_file:
      - ../../.env
    command: php artisan queue:work redis --verbose --tries=5 --timeout=120 --queue=local_market_webhooks
    depends_on:
      - app
    healthcheck:
      test: ["CMD", "php", "-r", "exit(0);"]
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 5
    networks:
      - laravel

  local-market-expire-trader-order-worker:
    image: app-php-fpm:latest
    working_dir: /var/www/html
    restart: unless-stopped
    env_file:
      - ../../.env
    command: php artisan queue:work redis --verbose --tries=50 --timeout=120 --queue=expire_trader_order
    depends_on:
      - app
    healthcheck:
      test: ["CMD", "php", "-r", "exit(0);"]
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 8
    networks:
      - laravel

  local-market-generate-units:
    image: app-php-fpm:latest
    working_dir: /var/www/html
    restart: unless-stopped
    env_file:
      - ../../.env
    command: php artisan queue:work redis --verbose --tries=3 --timeout=120 --queue=unit-inventory
    depends_on:
      - app
    healthcheck:
      test: ["CMD", "php", "-r", "exit(0);"]
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 1
    networks:
      - laravel

  buy-commodities-local-market-orders-worker:
    image: app-php-fpm:latest
    working_dir: /var/www/html
    restart: unless-stopped
    env_file:
      - ../../.env
    command: php artisan queue:work redis --verbose --tries=5 --timeout=120 --queue=buy_commodities_local_market_orders
    depends_on:
      - app
    healthcheck:
      test: ["CMD", "php", "-r", "exit(0);"]
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 5
    networks:
      - laravel

  notifications-worker:
    image: app-php-fpm:latest
    working_dir: /var/www/html
    restart: unless-stopped
    env_file:
      - ../../.env
    command: php artisan queue:work redis --verbose --tries=3 --timeout=120 --queue=notifications
    depends_on:
      - app
    healthcheck:
      test: ["CMD", "php", "-r", "exit(0);"]
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 5
    networks:
      - laravel

  bursam-worker:
    image: app-php-fpm:latest
    working_dir: /var/www/html
    restart: unless-stopped
    env_file:
      - ../../.env
    command: php artisan queue:work redis --verbose --tries=3 --timeout=120 --queue=bursam
    depends_on:
      - app
    healthcheck:
      test: ["CMD", "php", "-r", "exit(0);"]
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 1
    networks:
      - laravel

networks:
  laravel:
