name: Clone private repo on remote server

on:
  #push:
    #branches:
      #- dev
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Clone private repository
      run: | 
        ssh -o StrictHostKeyChecking=no ${{ secrets.USER_NAME }}@${{ secrets.DEV_IP }} \
         "git clone -o StrictHostKeyChecking=no git@github.com:abdulrahman-mohd/pipeline-test.git"