name: deploy on pre-production

on:
  workflow_dispatch:
  push:
    branches:
      - pre-production

jobs:
  deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) || github.event_name == 'workflow_dispatch'
    runs-on:
      group: pre-prod-runner-group
      labels: [self-hosted]
    steps:
      # Pull and build code on Backend Preprod Server 1
      - name: pulling and build code on backend preprod server 1
        id: pull-and-build-backend-preprod-server-1
        run: |
          ssh -i ~/.ssh/lynk-backend.pem -o StrictHostKeyChecking=no ${{ secrets.BACKEND_USER_PREPRD_1 }}@${{ secrets.BACKEND_PREPRD_1_IP }} \
           "cd /var/www/lynk-backend/ && sudo git pull origin pre-production && sudo composer install --no-interaction --prefer-dist --optimize-autoloader && sudo php artisan migrate --force && sudo php artisan package:discover && sudo php artisan structure:discover && sudo supervisorctl stop all && sudo supervisorctl start all"

      # Pull and build code on Backend Preprod Server 2
      - name: pulling and build code on backend preprod server 2
        id: pull-and-build-backend-preprod-server-2
        run: |
          ssh -i ~/.ssh/lynk-backend.pem -o StrictHostKeyChecking=no ${{ secrets.BACKEND_USER_PREPRD_2 }}@${{ secrets.BACKEND_PREPRD_2_IP }} \
           "cd /var/www/lynk-backend/ && sudo git pull origin pre-production && sudo composer install --no-interaction --prefer-dist --optimize-autoloader && sudo php artisan migrate --force && sudo php artisan structure:clear && sudo supervisorctl stop all && sudo supervisorctl start all"

      # Pull and build code on Backend Preprod Server 3
      - name: pulling and build code on backend preprod server 3
        id: pull-and-build-backend-preprod-server-3
        run: |
          ssh -i ~/.ssh/lynk-backend.pem -o StrictHostKeyChecking=no ${{ secrets.BACKEND_USER_PREPRD_3 }}@${{ secrets.BACKEND_PREPRD_3_IP }} \
           "cd /var/www/lynk-backend/ && sudo git pull origin pre-production && sudo composer install --no-interaction --prefer-dist --optimize-autoloader && sudo php artisan migrate --force && sudo php artisan structure:clear && sudo supervisorctl stop all && sudo supervisorctl start all"

      # Set PR URL if the event is 'pull_request' or 'pull_request_target'
      - name: set pr url
        if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target'
        id: pr-url
        uses: kceb/pull-request-url-action@v1
        with:
          github-oauth-token: ${{ secrets.GB_OAUTH_TOKEN }}

      - name: print info
        if: always()
        run: |
          echo "Repository Name: $GITHUB_REPOSITORY"
          echo "Branch Name: $GITHUB_REF"
          echo "pr-url: ${{ steps.pr-url.outputs.url }}"
          echo "Execution Time: $(date)"
          echo "Workflow Status: ${{ job.status }}"

          curl --insecure -X POST -H 'Content-type: application/json' --data '{"text":"Repository Name: '"$GITHUB_REPOSITORY"'\nBranch Name: '"$GITHUB_REF"'\nExecution Time: '"$(date)"'\nWorkflow Status: '"${{ job.status }}"'\n pull request URL: '"${{ steps.pr-url.outputs.url }}"'"}' ${{ secrets.SLACK_HOOK_URL }}